# Generated by Django 6.1 on 2026-08-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_updated', 'Status Updated'), ('incident_verified', 'Incident Verified'), ('dispatch_assigned', 'Dispatch Assigned'), ('duplicate_reviewed', 'Duplicate Reviewed'), ('report_linked', 'Report Linked To Incident'), ('note_added', 'Note Added')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_reference', models.CharField(blank=True, max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_a_created_446aad_idx')],
            },
        ),
    ]
