# Generated by Django 6.0.6 on 2026-08-31 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_updated', 'Status Updated'), ('incident_verified', 'Incident Verified'), ('dispatch_assigned', 'Dispatch Assigned'), ('duplicate_reviewed', 'Duplicate Reviewed'), ('report_linked', 'Report Linked To Incident'), ('note_added', 'Note Added'), ('settings_updated', 'Settings Updated'), ('account_updated', 'Account Updated'), ('data_exported', 'Data Exported')], max_length=30),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate_radius_m', models.PositiveIntegerField()),
                ('duplicate_window_minutes', models.PositiveIntegerField()),
                ('map_recent_hours', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
