# Generated by Django 6.0.6 on 2026-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_auditlog_action_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_updated', 'Status Updated'), ('incident_verified', 'Incident Verified'), ('dispatch_assigned', 'Dispatch Assigned'), ('duplicate_reviewed', 'Duplicate Reviewed'), ('report_linked', 'Report Linked To Incident'), ('note_added', 'Note Added'), ('settings_updated', 'Settings Updated'), ('account_updated', 'Account Updated'), ('data_exported', 'Data Exported'), ('login', 'Signed In')], max_length=30),
        ),
    ]
