# Generated by Django 6.0.6 on 2026-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_intake_rejected_unlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_updated', 'Status Updated'), ('incident_verified', 'Incident Verified'), ('dispatch_assigned', 'Dispatch Assigned'), ('duplicate_reviewed', 'Duplicate Reviewed'), ('report_linked', 'Report Linked To Incident'), ('settings_updated', 'Settings Updated'), ('account_updated', 'Account Updated'), ('data_exported', 'Data Exported'), ('login', 'Signed In'), ('report_unlinked', 'Report Unlinked From Incident'), ('report_encoded', 'Report Encoded')], max_length=30),
        ),
    ]
