"""Split the old `Incident` table into its true identity: a civilian report.

Hand-written rather than autogenerated. Left to itself, makemigrations sees a
model that vanished and a model that appeared, and emits DeleteModel +
CreateModel — which would drop every report already submitted. RenameModel and
RenameField preserve the rows and their primary keys, so existing reference
numbers (FT-YYYY-NNNNN) stay valid.

The name `Incident` is reused in the next migration for the new canonical
record, which is a genuinely different table.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incident',
            new_name='IncidentReport',
        ),
        # `status` was ambiguous once duplicate review became a second, separate
        # status dimension.
        migrations.RenameField(
            model_name='incidentreport',
            old_name='status',
            new_name='workflow_status',
        ),
    ]
