# Generated by Django 6.1 on 2026-08-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_rename_incident_to_incidentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_change', 'Status Change'), ('verification', 'Verification'), ('dispatch', 'Dispatch Assignment'), ('duplicate_flagged', 'Duplicate Flagged'), ('duplicate_review', 'Duplicate Review'), ('report_linked', 'Report Linked To Incident'), ('note', 'Note')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='duplicate_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_candidates', to='incidents.incidentreport'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='duplicate_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='duplicate_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='duplicate_status',
            field=models.CharField(choices=[('not_flagged', 'Not Flagged'), ('possible_duplicate', 'Possible Duplicate'), ('kept_separate', 'Kept Separate'), ('confirmed_duplicate', 'Confirmed Duplicate')], default='not_flagged', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='duplicate_time_delta_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='geocoding_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location_source',
            field=models.CharField(choices=[('map_pin', 'Pinned on map'), ('device_gps', 'Device GPS'), ('geocoded_address', 'Geocoded address'), ('barangay_only', 'Barangay only')], default='map_pin', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='report-photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('fire', 'Residential Fire'), ('vehicle', 'Vehicle Fire'), ('electrical', 'Electrical Fire'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('barangay', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('workflow_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('responding', 'Responding'), ('resolved', 'Resolved')], default='verified', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reports', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['workflow_status'], name='incidents_i_workflo_078f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['duplicate_status'], name='incidents_i_duplica_399844_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['created_at'], name='incidents_i_created_e00552_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['barangay'], name='incidents_i_baranga_bc2795_idx'),
        ),
        migrations.AddField(
            model_name='incidenttimelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenttimelineevent',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidenttimelineevent',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='incidents.incidentreport'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['workflow_status'], name='incidents_i_workflo_dd0dae_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='incidents_i_created_8be57d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenttimelineevent',
            index=models.Index(fields=['-created_at'], name='incidents_i_created_883e51_idx'),
        ),
    ]
