# Generated by Django 6.0.6 on 2026-09-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_backfill_geocoding_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
