# Generated by Django 6.0.6 on 2026-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_optional_description_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='caller_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='caller_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='source_channel',
            field=models.CharField(choices=[('pwa', 'FireTrace app'), ('hotline', 'Hotline call'), ('walk_in', 'Walk-in'), ('text', 'Text message'), ('radio', 'Radio'), ('referral', 'Inter-agency referral')], default='pwa', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenttimelineevent',
            name='event_type',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_change', 'Status Change'), ('verification', 'Verification'), ('dispatch', 'Dispatch Assignment'), ('duplicate_flagged', 'Duplicate Flagged'), ('duplicate_review', 'Duplicate Review'), ('report_linked', 'Report Linked To Incident'), ('note', 'Note'), ('report_unlinked', 'Report Unlinked From Incident')], max_length=30),
        ),
    ]
