# Generated by Django 6.0.6 on 2026-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_intake_rejected_unlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttimelineevent',
            name='event_type',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('status_change', 'Status Change'), ('verification', 'Verification'), ('dispatch', 'Dispatch Assignment'), ('duplicate_flagged', 'Duplicate Flagged'), ('duplicate_review', 'Duplicate Review'), ('report_linked', 'Report Linked To Incident'), ('report_unlinked', 'Report Unlinked From Incident')], max_length=30),
        ),
    ]
